server:
  port: 8081
logging:
  level:
    org.springframework: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    # Propiedad para BBDD H2 in memory
    url: jdbc:h2:mem:demo-liquibase;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
  jackson:
    default-property-inclusion: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # validate is desired but conflicts with H2
    properties:
      hibernate:
        dialect: ${spring.jpa.database-platform}
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog/changelog-master.yaml
    enabled: true
    password: ${spring.datasource.password}
    test-rollback-on-update: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
  main:
    lazy-initialization: true
